// <auto-generated />
using System;
using DSRProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSRProject.Migrations
{
    [DbContext(typeof(ValuteDbContext))]
    [Migration("20220430200532_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("DSRProject.Models.Course", b =>
                {
                    b.Property<uint>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.Property<string>("ValuteId")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.HasIndex("ValuteId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DSRProject.Models.Valute", b =>
                {
                    b.Property<string>("ValuteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nominal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("ValuteId");

                    b.ToTable("Valutes");
                });

            modelBuilder.Entity("DSRProject.Models.Course", b =>
                {
                    b.HasOne("DSRProject.Models.Valute", "Valute")
                        .WithMany()
                        .HasForeignKey("ValuteId");

                    b.Navigation("Valute");
                });
#pragma warning restore 612, 618
        }
    }
}
